import Ascent from '../../assets/maps/Ascent.png'
import Duality from '../../assets/maps/Bind.png'
import Foxtrot from '../../assets/maps/Breeze.png'
import Canyon from '../../assets/maps/Fracture.png'
import Triad from '../../assets/maps/Haven.png'
import Port from '../../assets/maps/Icebox.png'
import Bonsai from '../../assets/maps/Split.png'
import Ares from '../../assets/weapons/Ares.png'
import Bucky from '../../assets/weapons/Bucky.png'
import Bulldog from '../../assets/weapons/Bulldog.png'
import Classic from '../../assets/weapons/Classic.png'
import Frenzy from '../../assets/weapons/Frenzy.png'
import Ghost from '../../assets/weapons/Ghost.png'
import Golden_Gun from '../../assets/weapons/Golden_Gun.png'
import Guardian from '../../assets/weapons/Guardian.png'
import Judge from '../../assets/weapons/Judge.png'
import Marshal from '../../assets/weapons/Marshal.png'
import Odin from '../../assets/weapons/Odin.png'
import Operator from '../../assets/weapons/Operator.png'
import Phantom from '../../assets/weapons/Phantom.png'
import Sheriff from '../../assets/weapons/Sheriff.png'
import Shorty from '../../assets/weapons/Shorty.png'
import Spectre from '../../assets/weapons/Spectre.png'
import Stinger from '../../assets/weapons/Stinger.png'
import Tactical_Knife from '../../assets/weapons/Tactical_Knife.png'
import Vandal from '../../assets/weapons/Vandal.png'
import Astra from '../../assets/agents/Astra.png'
import Breach from '../../assets/agents/Breach.png'
import Brimstone from '../../assets/agents/Brimstone.png'
import Chamber from '../../assets/agents/Chamber.png'
import Cypher from '../../assets/agents/Cypher.png'
import Jett from '../../assets/agents/Jett.png'
import KAYO from '../../assets/agents/KAYO.png'
import Killjoy from '../../assets/agents/Killjoy.png'
import Neon from '../../assets/agents/Neon.png'
import Omen from '../../assets/agents/Omen.png'
import Phoenix from '../../assets/agents/Phoenix.png'
import Raze from '../../assets/agents/Raze.png'
import Reyna from '../../assets/agents/Reyna.png'
import Sage from '../../assets/agents/Sage.png'
import Skye from '../../assets/agents/Skye.png'
import Sova from '../../assets/agents/Sova.png'
import Viper from '../../assets/agents/Viper.png'
import Yoru from '../../assets/agents/Yoru.png'

export default {
    Ascent, Duality, Foxtrot, Canyon, Triad, Port, Bonsai, Ares, Bucky, Bulldog, Classic, Frenzy, Ghost,
    Golden_Gun, Guardian, Judge, Marshal, Odin, Operator, Phantom, Sheriff, Shorty, Spectre, Stinger, Tactical_Knife, Vandal,
    Astra, Breach, Brimstone, Chamber, Cypher, Jett, KAYO, Killjoy, Neon, Omen, Phoenix, Raze, Reyna, Sage, Skye, Sova, Viper, Yoru
}